# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scidirector.v1 import ai_service_pb2 as scidirector_dot_v1_dot_ai__service__pb2
from scidirector.v1 import common_pb2 as scidirector_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scidirector/v1/ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiDirectorServiceStub:
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/Health',
                request_serializer=scidirector_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_stream(
                '/scidirector.v1.AiDirectorService/RunPipeline',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_common__pb2.PipelineEvent.FromString,
                _registered_method=True)
        self.PlanScript = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/PlanScript',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.FromString,
                _registered_method=True)
        self.GenerateShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/GenerateShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.FromString,
                _registered_method=True)
        self.CritiqueShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/CritiqueShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.FromString,
                _registered_method=True)
        self.ReviseShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/ReviseShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.FromString,
                _registered_method=True)
        self.GetCheckpointSnapshot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/GetCheckpointSnapshot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotResponse.FromString,
                _registered_method=True)


class AiDirectorServiceServicer:
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    def Health(self, request, context):
        """就绪与能力探测。Go 侧在启动与熔断恢复时调用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """---------------------------------------------------------------------------
        粗粒度：把整条 LangGraph 交给 Python 跑，Go 只消费事件流并维护对外状态。
        注意：这是「长连接」，Go 侧必须设置足够大的超时与心跳策略。
        ---------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanScript(self, request, context):
        """---------------------------------------------------------------------------
        细粒度：人类反馈闭环（HITL）与调试用。
        ---------------------------------------------------------------------------

        仅执行导演智能体：脚本 -> 分镜表。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateShot(self, request, context):
        """仅执行编码 + 渲染：给定分镜（可选携带反馈）产出视频片段。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CritiqueShot(self, request, context):
        """仅执行审查：给定产物路径与抽帧，返回 VLM 审查意见。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviseShot(self, request, context):
        """人工意见回灌：把审核员的自然语言意见转成可执行指令，重新生成该镜头。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpointSnapshot(self, request, context):
        """---------------------------------------------------------------------------
        状态对账（阶段五）：读取某任务的 checkpoint 快照。

        **只读、无副作用。** Go 侧据此比对「Redis 里的对外状态」与
        「LangGraph checkpoint 里的续跑状态」，发现双写不一致。

        为什么由 Python 提供而不是让 Go 直接读 Postgres：
        checkpoint 的**存储格式是 LangGraph 的实现细节**（表结构、序列化方式都可能
        随版本变化）。让 Go 去解析它，等于把两个项目的内部实现焊在一起 ——
        一次 LangGraph 升级就会静默读出错的数据。因此由持有方读取，对外只暴露
        语义化字段。
        ---------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiDirectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=scidirector_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_common__pb2.PipelineEvent.SerializeToString,
            ),
            'PlanScript': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanScript,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.SerializeToString,
            ),
            'GenerateShot': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.SerializeToString,
            ),
            'CritiqueShot': grpc.unary_unary_rpc_method_handler(
                    servicer.CritiqueShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.SerializeToString,
            ),
            'ReviseShot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviseShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.SerializeToString,
            ),
            'GetCheckpointSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpointSnapshot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scidirector.v1.AiDirectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scidirector.v1.AiDirectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiDirectorService:
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/Health',
            scidirector_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            scidirector_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scidirector.v1.AiDirectorService/RunPipeline',
            scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.SerializeToString,
            scidirector_dot_v1_dot_common__pb2.PipelineEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/PlanScript',
            scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/GenerateShot',
            scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CritiqueShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/CritiqueShot',
            scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviseShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/ReviseShot',
            scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpointSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/GetCheckpointSnapshot',
            scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.CheckpointSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
