# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scidirector.v1 import ai_service_pb2 as scidirector_dot_v1_dot_ai__service__pb2
from scidirector.v1 import common_pb2 as scidirector_dot_v1_dot_common__pb2


class AiDirectorServiceStub(object):
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/Health',
                request_serializer=scidirector_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_stream(
                '/scidirector.v1.AiDirectorService/RunPipeline',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_common__pb2.PipelineEvent.FromString,
                _registered_method=True)
        self.PlanScript = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/PlanScript',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.FromString,
                _registered_method=True)
        self.GenerateShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/GenerateShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.FromString,
                _registered_method=True)
        self.CritiqueShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/CritiqueShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.FromString,
                _registered_method=True)
        self.ReviseShot = channel.unary_unary(
                '/scidirector.v1.AiDirectorService/ReviseShot',
                request_serializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.SerializeToString,
                response_deserializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.FromString,
                _registered_method=True)


class AiDirectorServiceServicer(object):
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    def Health(self, request, context):
        """就绪与能力探测。Go 侧在启动与熔断恢复时调用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """---------------------------------------------------------------------------
        粗粒度：把整条 LangGraph 交给 Python 跑，Go 只消费事件流并维护对外状态。
        注意：这是「长连接」，Go 侧必须设置足够大的超时与心跳策略。
        ---------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanScript(self, request, context):
        """---------------------------------------------------------------------------
        细粒度：人类反馈闭环（HITL）与调试用。
        ---------------------------------------------------------------------------

        仅执行导演智能体：脚本 -> 分镜表。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateShot(self, request, context):
        """仅执行编码 + 渲染：给定分镜（可选携带反馈）产出视频片段。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CritiqueShot(self, request, context):
        """仅执行审查：给定产物路径与抽帧，返回 VLM 审查意见。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviseShot(self, request, context):
        """人工意见回灌：把审核员的自然语言意见转成可执行指令，重新生成该镜头。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiDirectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=scidirector_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_common__pb2.PipelineEvent.SerializeToString,
            ),
            'PlanScript': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanScript,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.SerializeToString,
            ),
            'GenerateShot': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.SerializeToString,
            ),
            'CritiqueShot': grpc.unary_unary_rpc_method_handler(
                    servicer.CritiqueShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.SerializeToString,
            ),
            'ReviseShot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviseShot,
                    request_deserializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.FromString,
                    response_serializer=scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scidirector.v1.AiDirectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scidirector.v1.AiDirectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiDirectorService(object):
    """服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/Health',
            scidirector_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            scidirector_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scidirector.v1.AiDirectorService/RunPipeline',
            scidirector_dot_v1_dot_ai__service__pb2.RunPipelineRequest.SerializeToString,
            scidirector_dot_v1_dot_common__pb2.PipelineEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/PlanScript',
            scidirector_dot_v1_dot_ai__service__pb2.PlanScriptRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.PlanScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/GenerateShot',
            scidirector_dot_v1_dot_ai__service__pb2.GenerateShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.GenerateShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CritiqueShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/CritiqueShot',
            scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.CritiqueShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviseShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scidirector.v1.AiDirectorService/ReviseShot',
            scidirector_dot_v1_dot_ai__service__pb2.ReviseShotRequest.SerializeToString,
            scidirector_dot_v1_dot_ai__service__pb2.ReviseShotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
