// =============================================================================
// SciDirector AI 服务契约（Go 层 -> Python 大脑）
// -----------------------------------------------------------------------------
// 设计要点：
//   1) 粗粒度 RunPipeline 用「服务端流式」，让 Go 能实时把 导演/编码/渲染/审查
//      的每一步事件转发给 WebSocket，而不用轮询。
//   2) 细粒度 PlanScript / GenerateShot / CritiqueShot / ReviseShot 供 HITL
//      单点重做 —— 人类打回一个镜头时只重跑那一镜，不重跑全片（成本控制关键）。
//   3) 所有请求都携带 job_id / shot_id，保证两侧状态可对齐、日志可串联。
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: scidirector/v1/ai_service.proto

package scidirectorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiDirectorService_Health_FullMethodName       = "/scidirector.v1.AiDirectorService/Health"
	AiDirectorService_RunPipeline_FullMethodName  = "/scidirector.v1.AiDirectorService/RunPipeline"
	AiDirectorService_PlanScript_FullMethodName   = "/scidirector.v1.AiDirectorService/PlanScript"
	AiDirectorService_GenerateShot_FullMethodName = "/scidirector.v1.AiDirectorService/GenerateShot"
	AiDirectorService_CritiqueShot_FullMethodName = "/scidirector.v1.AiDirectorService/CritiqueShot"
	AiDirectorService_ReviseShot_FullMethodName   = "/scidirector.v1.AiDirectorService/ReviseShot"
)

// AiDirectorServiceClient is the client API for AiDirectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
type AiDirectorServiceClient interface {
	// 就绪与能力探测。Go 侧在启动与熔断恢复时调用。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ---------------------------------------------------------------------------
	// 粗粒度：把整条 LangGraph 交给 Python 跑，Go 只消费事件流并维护对外状态。
	// 注意：这是「长连接」，Go 侧必须设置足够大的超时与心跳策略。
	// ---------------------------------------------------------------------------
	RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error)
	// 仅执行导演智能体：脚本 -> 分镜表。
	PlanScript(ctx context.Context, in *PlanScriptRequest, opts ...grpc.CallOption) (*PlanScriptResponse, error)
	// 仅执行编码 + 渲染：给定分镜（可选携带反馈）产出视频片段。
	GenerateShot(ctx context.Context, in *GenerateShotRequest, opts ...grpc.CallOption) (*GenerateShotResponse, error)
	// 仅执行审查：给定产物路径与抽帧，返回 VLM 审查意见。
	CritiqueShot(ctx context.Context, in *CritiqueShotRequest, opts ...grpc.CallOption) (*CritiqueShotResponse, error)
	// 人工意见回灌：把审核员的自然语言意见转成可执行指令，重新生成该镜头。
	ReviseShot(ctx context.Context, in *ReviseShotRequest, opts ...grpc.CallOption) (*ReviseShotResponse, error)
}

type aiDirectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiDirectorServiceClient(cc grpc.ClientConnInterface) AiDirectorServiceClient {
	return &aiDirectorServiceClient{cc}
}

func (c *aiDirectorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AiDirectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiDirectorServiceClient) RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiDirectorService_ServiceDesc.Streams[0], AiDirectorService_RunPipeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunPipelineRequest, PipelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiDirectorService_RunPipelineClient = grpc.ServerStreamingClient[PipelineEvent]

func (c *aiDirectorServiceClient) PlanScript(ctx context.Context, in *PlanScriptRequest, opts ...grpc.CallOption) (*PlanScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanScriptResponse)
	err := c.cc.Invoke(ctx, AiDirectorService_PlanScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiDirectorServiceClient) GenerateShot(ctx context.Context, in *GenerateShotRequest, opts ...grpc.CallOption) (*GenerateShotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateShotResponse)
	err := c.cc.Invoke(ctx, AiDirectorService_GenerateShot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiDirectorServiceClient) CritiqueShot(ctx context.Context, in *CritiqueShotRequest, opts ...grpc.CallOption) (*CritiqueShotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CritiqueShotResponse)
	err := c.cc.Invoke(ctx, AiDirectorService_CritiqueShot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiDirectorServiceClient) ReviseShot(ctx context.Context, in *ReviseShotRequest, opts ...grpc.CallOption) (*ReviseShotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviseShotResponse)
	err := c.cc.Invoke(ctx, AiDirectorService_ReviseShot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiDirectorServiceServer is the server API for AiDirectorService service.
// All implementations must embed UnimplementedAiDirectorServiceServer
// for forward compatibility.
//
// 服务端并发策略：Python 侧用线程池处理阻塞型渲染调用。
type AiDirectorServiceServer interface {
	// 就绪与能力探测。Go 侧在启动与熔断恢复时调用。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ---------------------------------------------------------------------------
	// 粗粒度：把整条 LangGraph 交给 Python 跑，Go 只消费事件流并维护对外状态。
	// 注意：这是「长连接」，Go 侧必须设置足够大的超时与心跳策略。
	// ---------------------------------------------------------------------------
	RunPipeline(*RunPipelineRequest, grpc.ServerStreamingServer[PipelineEvent]) error
	// 仅执行导演智能体：脚本 -> 分镜表。
	PlanScript(context.Context, *PlanScriptRequest) (*PlanScriptResponse, error)
	// 仅执行编码 + 渲染：给定分镜（可选携带反馈）产出视频片段。
	GenerateShot(context.Context, *GenerateShotRequest) (*GenerateShotResponse, error)
	// 仅执行审查：给定产物路径与抽帧，返回 VLM 审查意见。
	CritiqueShot(context.Context, *CritiqueShotRequest) (*CritiqueShotResponse, error)
	// 人工意见回灌：把审核员的自然语言意见转成可执行指令，重新生成该镜头。
	ReviseShot(context.Context, *ReviseShotRequest) (*ReviseShotResponse, error)
	mustEmbedUnimplementedAiDirectorServiceServer()
}

// UnimplementedAiDirectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiDirectorServiceServer struct{}

func (UnimplementedAiDirectorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAiDirectorServiceServer) RunPipeline(*RunPipelineRequest, grpc.ServerStreamingServer[PipelineEvent]) error {
	return status.Error(codes.Unimplemented, "method RunPipeline not implemented")
}
func (UnimplementedAiDirectorServiceServer) PlanScript(context.Context, *PlanScriptRequest) (*PlanScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanScript not implemented")
}
func (UnimplementedAiDirectorServiceServer) GenerateShot(context.Context, *GenerateShotRequest) (*GenerateShotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateShot not implemented")
}
func (UnimplementedAiDirectorServiceServer) CritiqueShot(context.Context, *CritiqueShotRequest) (*CritiqueShotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CritiqueShot not implemented")
}
func (UnimplementedAiDirectorServiceServer) ReviseShot(context.Context, *ReviseShotRequest) (*ReviseShotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviseShot not implemented")
}
func (UnimplementedAiDirectorServiceServer) mustEmbedUnimplementedAiDirectorServiceServer() {}
func (UnimplementedAiDirectorServiceServer) testEmbeddedByValue()                           {}

// UnsafeAiDirectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiDirectorServiceServer will
// result in compilation errors.
type UnsafeAiDirectorServiceServer interface {
	mustEmbedUnimplementedAiDirectorServiceServer()
}

func RegisterAiDirectorServiceServer(s grpc.ServiceRegistrar, srv AiDirectorServiceServer) {
	// If the following call panics, it indicates UnimplementedAiDirectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiDirectorService_ServiceDesc, srv)
}

func _AiDirectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiDirectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiDirectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiDirectorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiDirectorService_RunPipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunPipelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiDirectorServiceServer).RunPipeline(m, &grpc.GenericServerStream[RunPipelineRequest, PipelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiDirectorService_RunPipelineServer = grpc.ServerStreamingServer[PipelineEvent]

func _AiDirectorService_PlanScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiDirectorServiceServer).PlanScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiDirectorService_PlanScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiDirectorServiceServer).PlanScript(ctx, req.(*PlanScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiDirectorService_GenerateShot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiDirectorServiceServer).GenerateShot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiDirectorService_GenerateShot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiDirectorServiceServer).GenerateShot(ctx, req.(*GenerateShotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiDirectorService_CritiqueShot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CritiqueShotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiDirectorServiceServer).CritiqueShot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiDirectorService_CritiqueShot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiDirectorServiceServer).CritiqueShot(ctx, req.(*CritiqueShotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiDirectorService_ReviseShot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviseShotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiDirectorServiceServer).ReviseShot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiDirectorService_ReviseShot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiDirectorServiceServer).ReviseShot(ctx, req.(*ReviseShotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiDirectorService_ServiceDesc is the grpc.ServiceDesc for AiDirectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiDirectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scidirector.v1.AiDirectorService",
	HandlerType: (*AiDirectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AiDirectorService_Health_Handler,
		},
		{
			MethodName: "PlanScript",
			Handler:    _AiDirectorService_PlanScript_Handler,
		},
		{
			MethodName: "GenerateShot",
			Handler:    _AiDirectorService_GenerateShot_Handler,
		},
		{
			MethodName: "CritiqueShot",
			Handler:    _AiDirectorService_CritiqueShot_Handler,
		},
		{
			MethodName: "ReviseShot",
			Handler:    _AiDirectorService_ReviseShot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunPipeline",
			Handler:       _AiDirectorService_RunPipeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scidirector/v1/ai_service.proto",
}
