// =============================================================================
// SciDirector AI 服务契约（Go 层 -> Python 大脑）
// -----------------------------------------------------------------------------
// 设计要点：
//   1) 粗粒度 RunPipeline 用「服务端流式」，让 Go 能实时把 导演/编码/渲染/审查
//      的每一步事件转发给 WebSocket，而不用轮询。
//   2) 细粒度 PlanScript / GenerateShot / CritiqueShot / ReviseShot 供 HITL
//      单点重做 —— 人类打回一个镜头时只重跑那一镜，不重跑全片（成本控制关键）。
//   3) 所有请求都携带 job_id / shot_id，保证两侧状态可对齐、日志可串联。
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: scidirector/v1/ai_service.proto

package scidirectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------------------------------------------------------------------------
// RunPipeline
// -----------------------------------------------------------------------------
type RunPipelineRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RawScript          string                 `protobuf:"bytes,2,opt,name=raw_script,json=rawScript,proto3" json:"raw_script,omitempty"`                                 // 用户原始脚本
	StyleGuideJson     string                 `protobuf:"bytes,3,opt,name=style_guide_json,json=styleGuideJson,proto3" json:"style_guide_json,omitempty"`                // 风格约束：配色、字体、语速、术语表
	TargetDurationSec  float64                `protobuf:"fixed64,4,opt,name=target_duration_sec,json=targetDurationSec,proto3" json:"target_duration_sec,omitempty"`     // 目标总时长，导演据此分配各镜头时长
	MaxAttemptsPerShot int32                  `protobuf:"varint,5,opt,name=max_attempts_per_shot,json=maxAttemptsPerShot,proto3" json:"max_attempts_per_shot,omitempty"` // 每镜头重试上限（熔断阈值）
	Locale             string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`                                                        // 语言/地区，影响 TTS 与字幕
	Resume             bool                   `protobuf:"varint,7,opt,name=resume,proto3" json:"resume,omitempty"`                                                       // true 时尝试从 Postgres checkpoint 续跑
	CheckpointThreadId string                 `protobuf:"bytes,8,opt,name=checkpoint_thread_id,json=checkpointThreadId,proto3" json:"checkpoint_thread_id,omitempty"`    // LangGraph 线程 ID，通常等于 job_id
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *RunPipelineRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunPipelineRequest) GetRawScript() string {
	if x != nil {
		return x.RawScript
	}
	return ""
}

func (x *RunPipelineRequest) GetStyleGuideJson() string {
	if x != nil {
		return x.StyleGuideJson
	}
	return ""
}

func (x *RunPipelineRequest) GetTargetDurationSec() float64 {
	if x != nil {
		return x.TargetDurationSec
	}
	return 0
}

func (x *RunPipelineRequest) GetMaxAttemptsPerShot() int32 {
	if x != nil {
		return x.MaxAttemptsPerShot
	}
	return 0
}

func (x *RunPipelineRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *RunPipelineRequest) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

func (x *RunPipelineRequest) GetCheckpointThreadId() string {
	if x != nil {
		return x.CheckpointThreadId
	}
	return ""
}

// -----------------------------------------------------------------------------
// PlanScript
// -----------------------------------------------------------------------------
type PlanScriptRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RawScript         string                 `protobuf:"bytes,2,opt,name=raw_script,json=rawScript,proto3" json:"raw_script,omitempty"`
	StyleGuideJson    string                 `protobuf:"bytes,3,opt,name=style_guide_json,json=styleGuideJson,proto3" json:"style_guide_json,omitempty"`
	TargetDurationSec float64                `protobuf:"fixed64,4,opt,name=target_duration_sec,json=targetDurationSec,proto3" json:"target_duration_sec,omitempty"`
	Locale            string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanScriptRequest) Reset() {
	*x = PlanScriptRequest{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanScriptRequest) ProtoMessage() {}

func (x *PlanScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanScriptRequest.ProtoReflect.Descriptor instead.
func (*PlanScriptRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *PlanScriptRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PlanScriptRequest) GetRawScript() string {
	if x != nil {
		return x.RawScript
	}
	return ""
}

func (x *PlanScriptRequest) GetStyleGuideJson() string {
	if x != nil {
		return x.StyleGuideJson
	}
	return ""
}

func (x *PlanScriptRequest) GetTargetDurationSec() float64 {
	if x != nil {
		return x.TargetDurationSec
	}
	return 0
}

func (x *PlanScriptRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type PlanScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shots         []*ShotSpec            `protobuf:"bytes,1,rep,name=shots,proto3" json:"shots,omitempty"`
	Outline       string                 `protobuf:"bytes,2,opt,name=outline,proto3" json:"outline,omitempty"`                             // 全片叙事大纲，便于人工审核与调试
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"` // 成本可观测量
	ElapsedSec    float64                `protobuf:"fixed64,4,opt,name=elapsed_sec,json=elapsedSec,proto3" json:"elapsed_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanScriptResponse) Reset() {
	*x = PlanScriptResponse{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanScriptResponse) ProtoMessage() {}

func (x *PlanScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanScriptResponse.ProtoReflect.Descriptor instead.
func (*PlanScriptResponse) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *PlanScriptResponse) GetShots() []*ShotSpec {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *PlanScriptResponse) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *PlanScriptResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *PlanScriptResponse) GetElapsedSec() float64 {
	if x != nil {
		return x.ElapsedSec
	}
	return 0
}

// -----------------------------------------------------------------------------
// GenerateShot
// -----------------------------------------------------------------------------
type GenerateShotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Shot           *ShotSpec              `protobuf:"bytes,2,opt,name=shot,proto3" json:"shot,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`  // 第几次尝试（从 1 开始）
	Feedback       *CriticFeedback        `protobuf:"bytes,4,opt,name=feedback,proto3" json:"feedback,omitempty"` // 上一轮的审查/人工意见，用于修正式重写
	StyleGuideJson string                 `protobuf:"bytes,5,opt,name=style_guide_json,json=styleGuideJson,proto3" json:"style_guide_json,omitempty"`
	DraftOnly      bool                   `protobuf:"varint,6,opt,name=draft_only,json=draftOnly,proto3" json:"draft_only,omitempty"` // true=低分辨率草稿渲染，用于先验证再高清重渲
	OutputDir      string                 `protobuf:"bytes,7,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`  // Go 指定的产物目录，保证两侧路径一致
	// ---- 局部重渲染（阶段三）----
	//
	// 只重渲镜头的某一段，而不是整镜，用于「只改了一处细节」的场景。
	//
	// 只在**时间轴可控**的引擎上有意义：AMBIENCE（lavfi）与 HTML（逐帧 seek）
	// 可以按秒精确截取；MATH/Manim 是按动画序号驱动渲染的，
	// 「第 3~5 秒」无法可靠映射到动画区间，因此对该引擎会忽略这两个字段
	// 并整镜重渲（由 `partial_range_honored` 如实回填）。
	//
	// range_end_sec <= range_start_sec 表示不启用局部重渲（整镜渲染）。
	RangeStartSec float64 `protobuf:"fixed64,8,opt,name=range_start_sec,json=rangeStartSec,proto3" json:"range_start_sec,omitempty"`
	RangeEndSec   float64 `protobuf:"fixed64,9,opt,name=range_end_sec,json=rangeEndSec,proto3" json:"range_end_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateShotRequest) Reset() {
	*x = GenerateShotRequest{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShotRequest) ProtoMessage() {}

func (x *GenerateShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShotRequest.ProtoReflect.Descriptor instead.
func (*GenerateShotRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateShotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateShotRequest) GetShot() *ShotSpec {
	if x != nil {
		return x.Shot
	}
	return nil
}

func (x *GenerateShotRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *GenerateShotRequest) GetFeedback() *CriticFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *GenerateShotRequest) GetStyleGuideJson() string {
	if x != nil {
		return x.StyleGuideJson
	}
	return ""
}

func (x *GenerateShotRequest) GetDraftOnly() bool {
	if x != nil {
		return x.DraftOnly
	}
	return false
}

func (x *GenerateShotRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *GenerateShotRequest) GetRangeStartSec() float64 {
	if x != nil {
		return x.RangeStartSec
	}
	return 0
}

func (x *GenerateShotRequest) GetRangeEndSec() float64 {
	if x != nil {
		return x.RangeEndSec
	}
	return 0
}

type GenerateShotResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Shot        *ShotSpec              `protobuf:"bytes,1,opt,name=shot,proto3" json:"shot,omitempty"` // 回填 code / engine 等字段后的分镜
	Artifact    *RenderArtifact        `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Success     bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error       string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // 技术性失败原因（编译错误、超时等）
	TotalTokens int32                  `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ElapsedSec  float64                `protobuf:"fixed64,6,opt,name=elapsed_sec,json=elapsedSec,proto3" json:"elapsed_sec,omitempty"`
	// partial_range_honored 表示本次是否真的只渲染了请求的时间区间。
	// 必须如实回填：Go 侧据此决定是「直接替换该区间」还是「整镜替换」，
	// 猜错的后果是把只渲染了 2 秒的片段当成完整镜头拼进成片。
	PartialRangeHonored bool `protobuf:"varint,7,opt,name=partial_range_honored,json=partialRangeHonored,proto3" json:"partial_range_honored,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateShotResponse) Reset() {
	*x = GenerateShotResponse{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShotResponse) ProtoMessage() {}

func (x *GenerateShotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShotResponse.ProtoReflect.Descriptor instead.
func (*GenerateShotResponse) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateShotResponse) GetShot() *ShotSpec {
	if x != nil {
		return x.Shot
	}
	return nil
}

func (x *GenerateShotResponse) GetArtifact() *RenderArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GenerateShotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateShotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GenerateShotResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *GenerateShotResponse) GetElapsedSec() float64 {
	if x != nil {
		return x.ElapsedSec
	}
	return 0
}

func (x *GenerateShotResponse) GetPartialRangeHonored() bool {
	if x != nil {
		return x.PartialRangeHonored
	}
	return false
}

// -----------------------------------------------------------------------------
// CritiqueShot
// -----------------------------------------------------------------------------
type CritiqueShotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Shot           *ShotSpec              `protobuf:"bytes,2,opt,name=shot,proto3" json:"shot,omitempty"`
	Artifact       *RenderArtifact        `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Attempt        int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StyleGuideJson string                 `protobuf:"bytes,5,opt,name=style_guide_json,json=styleGuideJson,proto3" json:"style_guide_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CritiqueShotRequest) Reset() {
	*x = CritiqueShotRequest{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CritiqueShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CritiqueShotRequest) ProtoMessage() {}

func (x *CritiqueShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CritiqueShotRequest.ProtoReflect.Descriptor instead.
func (*CritiqueShotRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *CritiqueShotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CritiqueShotRequest) GetShot() *ShotSpec {
	if x != nil {
		return x.Shot
	}
	return nil
}

func (x *CritiqueShotRequest) GetArtifact() *RenderArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *CritiqueShotRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *CritiqueShotRequest) GetStyleGuideJson() string {
	if x != nil {
		return x.StyleGuideJson
	}
	return ""
}

type CritiqueShotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *CriticFeedback        `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Degraded      bool                   `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"` // true=模型不可用，走了降级策略（转人工）
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ElapsedSec    float64                `protobuf:"fixed64,4,opt,name=elapsed_sec,json=elapsedSec,proto3" json:"elapsed_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CritiqueShotResponse) Reset() {
	*x = CritiqueShotResponse{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CritiqueShotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CritiqueShotResponse) ProtoMessage() {}

func (x *CritiqueShotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CritiqueShotResponse.ProtoReflect.Descriptor instead.
func (*CritiqueShotResponse) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *CritiqueShotResponse) GetFeedback() *CriticFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *CritiqueShotResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *CritiqueShotResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *CritiqueShotResponse) GetElapsedSec() float64 {
	if x != nil {
		return x.ElapsedSec
	}
	return 0
}

// -----------------------------------------------------------------------------
// ReviseShot（人工反馈回灌）
// -----------------------------------------------------------------------------
type ReviseShotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Shot           *ShotSpec              `protobuf:"bytes,2,opt,name=shot,proto3" json:"shot,omitempty"`
	HumanComment   string                 `protobuf:"bytes,3,opt,name=human_comment,json=humanComment,proto3" json:"human_comment,omitempty"` // 审核员自然语言意见，如「坐标轴标签重叠了」
	Attempt        int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StyleGuideJson string                 `protobuf:"bytes,5,opt,name=style_guide_json,json=styleGuideJson,proto3" json:"style_guide_json,omitempty"`
	OutputDir      string                 `protobuf:"bytes,6,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	// ---- 局部重渲染（阶段三）----
	//
	// 人工反馈最主要的入口。审核员指出「第 3 秒坐标轴标签重叠了」时，
	// 前端把意见对应的时间点填进来，即可只重渲这一段而不是整个镜头。
	// 语义与 GenerateShotRequest 的同名字段一致；
	// range_end_sec <= range_start_sec 表示整镜重渲。
	RangeStartSec float64 `protobuf:"fixed64,7,opt,name=range_start_sec,json=rangeStartSec,proto3" json:"range_start_sec,omitempty"`
	RangeEndSec   float64 `protobuf:"fixed64,8,opt,name=range_end_sec,json=rangeEndSec,proto3" json:"range_end_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviseShotRequest) Reset() {
	*x = ReviseShotRequest{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviseShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviseShotRequest) ProtoMessage() {}

func (x *ReviseShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviseShotRequest.ProtoReflect.Descriptor instead.
func (*ReviseShotRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReviseShotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReviseShotRequest) GetShot() *ShotSpec {
	if x != nil {
		return x.Shot
	}
	return nil
}

func (x *ReviseShotRequest) GetHumanComment() string {
	if x != nil {
		return x.HumanComment
	}
	return ""
}

func (x *ReviseShotRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReviseShotRequest) GetStyleGuideJson() string {
	if x != nil {
		return x.StyleGuideJson
	}
	return ""
}

func (x *ReviseShotRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ReviseShotRequest) GetRangeStartSec() float64 {
	if x != nil {
		return x.RangeStartSec
	}
	return 0
}

func (x *ReviseShotRequest) GetRangeEndSec() float64 {
	if x != nil {
		return x.RangeEndSec
	}
	return 0
}

type ReviseShotResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Shot        *ShotSpec              `protobuf:"bytes,1,opt,name=shot,proto3" json:"shot,omitempty"` // 含改写后的源码
	Artifact    *RenderArtifact        `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Feedback    *CriticFeedback        `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"` // 自动复审结果；供 UI 展示是否已修好
	Success     bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error       string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	TotalTokens int32                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ElapsedSec  float64                `protobuf:"fixed64,7,opt,name=elapsed_sec,json=elapsedSec,proto3" json:"elapsed_sec,omitempty"`
	// 见 GenerateShotResponse.partial_range_honored。
	PartialRangeHonored bool `protobuf:"varint,8,opt,name=partial_range_honored,json=partialRangeHonored,proto3" json:"partial_range_honored,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReviseShotResponse) Reset() {
	*x = ReviseShotResponse{}
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviseShotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviseShotResponse) ProtoMessage() {}

func (x *ReviseShotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviseShotResponse.ProtoReflect.Descriptor instead.
func (*ReviseShotResponse) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReviseShotResponse) GetShot() *ShotSpec {
	if x != nil {
		return x.Shot
	}
	return nil
}

func (x *ReviseShotResponse) GetArtifact() *RenderArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ReviseShotResponse) GetFeedback() *CriticFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ReviseShotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReviseShotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReviseShotResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ReviseShotResponse) GetElapsedSec() float64 {
	if x != nil {
		return x.ElapsedSec
	}
	return 0
}

func (x *ReviseShotResponse) GetPartialRangeHonored() bool {
	if x != nil {
		return x.PartialRangeHonored
	}
	return false
}

var File_scidirector_v1_ai_service_proto protoreflect.FileDescriptor

const file_scidirector_v1_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x1fscidirector/v1/ai_service.proto\x12\x0escidirector.v1\x1a\x1bscidirector/v1/common.proto\"\xb9\x02\n" +
	"\x12RunPipelineRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"raw_script\x18\x02 \x01(\tR\trawScript\x12(\n" +
	"\x10style_guide_json\x18\x03 \x01(\tR\x0estyleGuideJson\x12.\n" +
	"\x13target_duration_sec\x18\x04 \x01(\x01R\x11targetDurationSec\x121\n" +
	"\x15max_attempts_per_shot\x18\x05 \x01(\x05R\x12maxAttemptsPerShot\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12\x16\n" +
	"\x06resume\x18\a \x01(\bR\x06resume\x120\n" +
	"\x14checkpoint_thread_id\x18\b \x01(\tR\x12checkpointThreadId\"\xbb\x01\n" +
	"\x11PlanScriptRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"raw_script\x18\x02 \x01(\tR\trawScript\x12(\n" +
	"\x10style_guide_json\x18\x03 \x01(\tR\x0estyleGuideJson\x12.\n" +
	"\x13target_duration_sec\x18\x04 \x01(\x01R\x11targetDurationSec\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\"\xa2\x01\n" +
	"\x12PlanScriptResponse\x12.\n" +
	"\x05shots\x18\x01 \x03(\v2\x18.scidirector.v1.ShotSpecR\x05shots\x12\x18\n" +
	"\aoutline\x18\x02 \x01(\tR\aoutline\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\velapsed_sec\x18\x04 \x01(\x01R\n" +
	"elapsedSec\"\xe4\x02\n" +
	"\x13GenerateShotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x04shot\x18\x02 \x01(\v2\x18.scidirector.v1.ShotSpecR\x04shot\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12:\n" +
	"\bfeedback\x18\x04 \x01(\v2\x1e.scidirector.v1.CriticFeedbackR\bfeedback\x12(\n" +
	"\x10style_guide_json\x18\x05 \x01(\tR\x0estyleGuideJson\x12\x1d\n" +
	"\n" +
	"draft_only\x18\x06 \x01(\bR\tdraftOnly\x12\x1d\n" +
	"\n" +
	"output_dir\x18\a \x01(\tR\toutputDir\x12&\n" +
	"\x0frange_start_sec\x18\b \x01(\x01R\rrangeStartSec\x12\"\n" +
	"\rrange_end_sec\x18\t \x01(\x01R\vrangeEndSec\"\xa8\x02\n" +
	"\x14GenerateShotResponse\x12,\n" +
	"\x04shot\x18\x01 \x01(\v2\x18.scidirector.v1.ShotSpecR\x04shot\x12:\n" +
	"\bartifact\x18\x02 \x01(\v2\x1e.scidirector.v1.RenderArtifactR\bartifact\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\ftotal_tokens\x18\x05 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\velapsed_sec\x18\x06 \x01(\x01R\n" +
	"elapsedSec\x122\n" +
	"\x15partial_range_honored\x18\a \x01(\bR\x13partialRangeHonored\"\xda\x01\n" +
	"\x13CritiqueShotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x04shot\x18\x02 \x01(\v2\x18.scidirector.v1.ShotSpecR\x04shot\x12:\n" +
	"\bartifact\x18\x03 \x01(\v2\x1e.scidirector.v1.RenderArtifactR\bartifact\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12(\n" +
	"\x10style_guide_json\x18\x05 \x01(\tR\x0estyleGuideJson\"\xb2\x01\n" +
	"\x14CritiqueShotResponse\x12:\n" +
	"\bfeedback\x18\x01 \x01(\v2\x1e.scidirector.v1.CriticFeedbackR\bfeedback\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\velapsed_sec\x18\x04 \x01(\x01R\n" +
	"elapsedSec\"\xac\x02\n" +
	"\x11ReviseShotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x04shot\x18\x02 \x01(\v2\x18.scidirector.v1.ShotSpecR\x04shot\x12#\n" +
	"\rhuman_comment\x18\x03 \x01(\tR\fhumanComment\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12(\n" +
	"\x10style_guide_json\x18\x05 \x01(\tR\x0estyleGuideJson\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x06 \x01(\tR\toutputDir\x12&\n" +
	"\x0frange_start_sec\x18\a \x01(\x01R\rrangeStartSec\x12\"\n" +
	"\rrange_end_sec\x18\b \x01(\x01R\vrangeEndSec\"\xe2\x02\n" +
	"\x12ReviseShotResponse\x12,\n" +
	"\x04shot\x18\x01 \x01(\v2\x18.scidirector.v1.ShotSpecR\x04shot\x12:\n" +
	"\bartifact\x18\x02 \x01(\v2\x1e.scidirector.v1.RenderArtifactR\bartifact\x12:\n" +
	"\bfeedback\x18\x03 \x01(\v2\x1e.scidirector.v1.CriticFeedbackR\bfeedback\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\velapsed_sec\x18\a \x01(\x01R\n" +
	"elapsedSec\x122\n" +
	"\x15partial_range_honored\x18\b \x01(\bR\x13partialRangeHonored2\x90\x04\n" +
	"\x11AiDirectorService\x12G\n" +
	"\x06Health\x12\x1d.scidirector.v1.HealthRequest\x1a\x1e.scidirector.v1.HealthResponse\x12R\n" +
	"\vRunPipeline\x12\".scidirector.v1.RunPipelineRequest\x1a\x1d.scidirector.v1.PipelineEvent0\x01\x12S\n" +
	"\n" +
	"PlanScript\x12!.scidirector.v1.PlanScriptRequest\x1a\".scidirector.v1.PlanScriptResponse\x12Y\n" +
	"\fGenerateShot\x12#.scidirector.v1.GenerateShotRequest\x1a$.scidirector.v1.GenerateShotResponse\x12Y\n" +
	"\fCritiqueShot\x12#.scidirector.v1.CritiqueShotRequest\x1a$.scidirector.v1.CritiqueShotResponse\x12S\n" +
	"\n" +
	"ReviseShot\x12!.scidirector.v1.ReviseShotRequest\x1a\".scidirector.v1.ReviseShotResponseBQZOgithub.com/itJinYu/SciDirector/backend/internal/pb/scidirector/v1;scidirectorv1b\x06proto3"

var (
	file_scidirector_v1_ai_service_proto_rawDescOnce sync.Once
	file_scidirector_v1_ai_service_proto_rawDescData []byte
)

func file_scidirector_v1_ai_service_proto_rawDescGZIP() []byte {
	file_scidirector_v1_ai_service_proto_rawDescOnce.Do(func() {
		file_scidirector_v1_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scidirector_v1_ai_service_proto_rawDesc), len(file_scidirector_v1_ai_service_proto_rawDesc)))
	})
	return file_scidirector_v1_ai_service_proto_rawDescData
}

var file_scidirector_v1_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scidirector_v1_ai_service_proto_goTypes = []any{
	(*RunPipelineRequest)(nil),   // 0: scidirector.v1.RunPipelineRequest
	(*PlanScriptRequest)(nil),    // 1: scidirector.v1.PlanScriptRequest
	(*PlanScriptResponse)(nil),   // 2: scidirector.v1.PlanScriptResponse
	(*GenerateShotRequest)(nil),  // 3: scidirector.v1.GenerateShotRequest
	(*GenerateShotResponse)(nil), // 4: scidirector.v1.GenerateShotResponse
	(*CritiqueShotRequest)(nil),  // 5: scidirector.v1.CritiqueShotRequest
	(*CritiqueShotResponse)(nil), // 6: scidirector.v1.CritiqueShotResponse
	(*ReviseShotRequest)(nil),    // 7: scidirector.v1.ReviseShotRequest
	(*ReviseShotResponse)(nil),   // 8: scidirector.v1.ReviseShotResponse
	(*ShotSpec)(nil),             // 9: scidirector.v1.ShotSpec
	(*CriticFeedback)(nil),       // 10: scidirector.v1.CriticFeedback
	(*RenderArtifact)(nil),       // 11: scidirector.v1.RenderArtifact
	(*HealthRequest)(nil),        // 12: scidirector.v1.HealthRequest
	(*HealthResponse)(nil),       // 13: scidirector.v1.HealthResponse
	(*PipelineEvent)(nil),        // 14: scidirector.v1.PipelineEvent
}
var file_scidirector_v1_ai_service_proto_depIdxs = []int32{
	9,  // 0: scidirector.v1.PlanScriptResponse.shots:type_name -> scidirector.v1.ShotSpec
	9,  // 1: scidirector.v1.GenerateShotRequest.shot:type_name -> scidirector.v1.ShotSpec
	10, // 2: scidirector.v1.GenerateShotRequest.feedback:type_name -> scidirector.v1.CriticFeedback
	9,  // 3: scidirector.v1.GenerateShotResponse.shot:type_name -> scidirector.v1.ShotSpec
	11, // 4: scidirector.v1.GenerateShotResponse.artifact:type_name -> scidirector.v1.RenderArtifact
	9,  // 5: scidirector.v1.CritiqueShotRequest.shot:type_name -> scidirector.v1.ShotSpec
	11, // 6: scidirector.v1.CritiqueShotRequest.artifact:type_name -> scidirector.v1.RenderArtifact
	10, // 7: scidirector.v1.CritiqueShotResponse.feedback:type_name -> scidirector.v1.CriticFeedback
	9,  // 8: scidirector.v1.ReviseShotRequest.shot:type_name -> scidirector.v1.ShotSpec
	9,  // 9: scidirector.v1.ReviseShotResponse.shot:type_name -> scidirector.v1.ShotSpec
	11, // 10: scidirector.v1.ReviseShotResponse.artifact:type_name -> scidirector.v1.RenderArtifact
	10, // 11: scidirector.v1.ReviseShotResponse.feedback:type_name -> scidirector.v1.CriticFeedback
	12, // 12: scidirector.v1.AiDirectorService.Health:input_type -> scidirector.v1.HealthRequest
	0,  // 13: scidirector.v1.AiDirectorService.RunPipeline:input_type -> scidirector.v1.RunPipelineRequest
	1,  // 14: scidirector.v1.AiDirectorService.PlanScript:input_type -> scidirector.v1.PlanScriptRequest
	3,  // 15: scidirector.v1.AiDirectorService.GenerateShot:input_type -> scidirector.v1.GenerateShotRequest
	5,  // 16: scidirector.v1.AiDirectorService.CritiqueShot:input_type -> scidirector.v1.CritiqueShotRequest
	7,  // 17: scidirector.v1.AiDirectorService.ReviseShot:input_type -> scidirector.v1.ReviseShotRequest
	13, // 18: scidirector.v1.AiDirectorService.Health:output_type -> scidirector.v1.HealthResponse
	14, // 19: scidirector.v1.AiDirectorService.RunPipeline:output_type -> scidirector.v1.PipelineEvent
	2,  // 20: scidirector.v1.AiDirectorService.PlanScript:output_type -> scidirector.v1.PlanScriptResponse
	4,  // 21: scidirector.v1.AiDirectorService.GenerateShot:output_type -> scidirector.v1.GenerateShotResponse
	6,  // 22: scidirector.v1.AiDirectorService.CritiqueShot:output_type -> scidirector.v1.CritiqueShotResponse
	8,  // 23: scidirector.v1.AiDirectorService.ReviseShot:output_type -> scidirector.v1.ReviseShotResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_scidirector_v1_ai_service_proto_init() }
func file_scidirector_v1_ai_service_proto_init() {
	if File_scidirector_v1_ai_service_proto != nil {
		return
	}
	file_scidirector_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scidirector_v1_ai_service_proto_rawDesc), len(file_scidirector_v1_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scidirector_v1_ai_service_proto_goTypes,
		DependencyIndexes: file_scidirector_v1_ai_service_proto_depIdxs,
		MessageInfos:      file_scidirector_v1_ai_service_proto_msgTypes,
	}.Build()
	File_scidirector_v1_ai_service_proto = out.File
	file_scidirector_v1_ai_service_proto_goTypes = nil
	file_scidirector_v1_ai_service_proto_depIdxs = nil
}
