// =============================================================================
// SciDirector 跨语言公共契约
// -----------------------------------------------------------------------------
// 该文件是 Go 层与 Python 层之间的「唯一真源」。任何字段改动都必须：
//   1) 遵循 proto3 兼容规则（只增不改 tag，不复用已删除的字段号）
//   2) 执行 `make proto` 重新生成两侧代码
//   3) 同步更新 docs/API.md 与 Agent.md §5 的智能体契约
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: scidirector/v1/common.proto

package scidirectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------------------------------------------------------------------------
// 场景标签：由导演智能体打标，决定后续「编码智能体」的路由目标。
// 这是整套路由逻辑的枢纽 —— 标签错了，后面全错。
// -----------------------------------------------------------------------------
type SceneTag int32

const (
	SceneTag_SCENE_TAG_UNSPECIFIED SceneTag = 0
	// [数学] 公式推导、几何演示 -> Manim（LaTeX 排版，符号天然正确）
	SceneTag_SCENE_TAG_MATH SceneTag = 1
	// [数据] 统计图表、趋势对比 -> D3.js / ECharts（数值来自脚本，坐标轴由代码决定）
	SceneTag_SCENE_TAG_DATA SceneTag = 2
	// [代码] 算法讲解、代码演示 -> 语法高亮打字动画
	SceneTag_SCENE_TAG_CODE SceneTag = 3
	// [氛围] 过渡、情绪铺陈、实拍感空镜 -> 素材检索 / 渐变占位
	SceneTag_SCENE_TAG_AMBIENCE SceneTag = 4
)

// Enum value maps for SceneTag.
var (
	SceneTag_name = map[int32]string{
		0: "SCENE_TAG_UNSPECIFIED",
		1: "SCENE_TAG_MATH",
		2: "SCENE_TAG_DATA",
		3: "SCENE_TAG_CODE",
		4: "SCENE_TAG_AMBIENCE",
	}
	SceneTag_value = map[string]int32{
		"SCENE_TAG_UNSPECIFIED": 0,
		"SCENE_TAG_MATH":        1,
		"SCENE_TAG_DATA":        2,
		"SCENE_TAG_CODE":        3,
		"SCENE_TAG_AMBIENCE":    4,
	}
)

func (x SceneTag) Enum() *SceneTag {
	p := new(SceneTag)
	*p = x
	return p
}

func (x SceneTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneTag) Descriptor() protoreflect.EnumDescriptor {
	return file_scidirector_v1_common_proto_enumTypes[0].Descriptor()
}

func (SceneTag) Type() protoreflect.EnumType {
	return &file_scidirector_v1_common_proto_enumTypes[0]
}

func (x SceneTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneTag.Descriptor instead.
func (SceneTag) EnumDescriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{0}
}

// -----------------------------------------------------------------------------
// 渲染引擎：由标签「确定性映射」得到，不允许模型自由发挥。
// 映射表见 Agent.md §5.2。
// -----------------------------------------------------------------------------
type RenderEngine int32

const (
	RenderEngine_RENDER_ENGINE_UNSPECIFIED RenderEngine = 0
	RenderEngine_RENDER_ENGINE_MANIM       RenderEngine = 1 // Python + Manim + LaTeX
	RenderEngine_RENDER_ENGINE_D3          RenderEngine = 2 // HTML + D3.js，headless 浏览器录制
	RenderEngine_RENDER_ENGINE_ECHARTS     RenderEngine = 3 // HTML + ECharts，headless 浏览器录制
	RenderEngine_RENDER_ENGINE_CODE_ANIM   RenderEngine = 4 // 代码高亮打字动画
	RenderEngine_RENDER_ENGINE_STOCK       RenderEngine = 5 // 素材检索 / 程序化渐变兜底
)

// Enum value maps for RenderEngine.
var (
	RenderEngine_name = map[int32]string{
		0: "RENDER_ENGINE_UNSPECIFIED",
		1: "RENDER_ENGINE_MANIM",
		2: "RENDER_ENGINE_D3",
		3: "RENDER_ENGINE_ECHARTS",
		4: "RENDER_ENGINE_CODE_ANIM",
		5: "RENDER_ENGINE_STOCK",
	}
	RenderEngine_value = map[string]int32{
		"RENDER_ENGINE_UNSPECIFIED": 0,
		"RENDER_ENGINE_MANIM":       1,
		"RENDER_ENGINE_D3":          2,
		"RENDER_ENGINE_ECHARTS":     3,
		"RENDER_ENGINE_CODE_ANIM":   4,
		"RENDER_ENGINE_STOCK":       5,
	}
)

func (x RenderEngine) Enum() *RenderEngine {
	p := new(RenderEngine)
	*p = x
	return p
}

func (x RenderEngine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderEngine) Descriptor() protoreflect.EnumDescriptor {
	return file_scidirector_v1_common_proto_enumTypes[1].Descriptor()
}

func (RenderEngine) Type() protoreflect.EnumType {
	return &file_scidirector_v1_common_proto_enumTypes[1]
}

func (x RenderEngine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderEngine.Descriptor instead.
func (RenderEngine) EnumDescriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{1}
}

// -----------------------------------------------------------------------------
// 分镜状态机：合法迁移在 backend/internal/domain/state.go 中硬编码。
// 流程图见 docs/DESIGN.md 与 Agent.md §6。
// -----------------------------------------------------------------------------
type ShotStatus int32

const (
	ShotStatus_SHOT_STATUS_UNSPECIFIED    ShotStatus = 0
	ShotStatus_SHOT_STATUS_PENDING        ShotStatus = 1 // 待生成
	ShotStatus_SHOT_STATUS_GENERATING     ShotStatus = 2 // 生成中（LLM 正在写代码 / 改代码）
	ShotStatus_SHOT_STATUS_RENDERING      ShotStatus = 3 // 渲染中（沙盒执行代码）
	ShotStatus_SHOT_STATUS_CRITIQUING     ShotStatus = 4 // 审查中（VLM 看帧）
	ShotStatus_SHOT_STATUS_APPROVED       ShotStatus = 5 // 已完成
	ShotStatus_SHOT_STATUS_REJECTED       ShotStatus = 6 // 已打回（语义不合格）
	ShotStatus_SHOT_STATUS_RETRYING       ShotStatus = 7 // 重试中
	ShotStatus_SHOT_STATUS_FAILED         ShotStatus = 8 // 失败（技术性失败）
	ShotStatus_SHOT_STATUS_AWAITING_HUMAN ShotStatus = 9 // 等待人工介入（重试达上限，熔断）
)

// Enum value maps for ShotStatus.
var (
	ShotStatus_name = map[int32]string{
		0: "SHOT_STATUS_UNSPECIFIED",
		1: "SHOT_STATUS_PENDING",
		2: "SHOT_STATUS_GENERATING",
		3: "SHOT_STATUS_RENDERING",
		4: "SHOT_STATUS_CRITIQUING",
		5: "SHOT_STATUS_APPROVED",
		6: "SHOT_STATUS_REJECTED",
		7: "SHOT_STATUS_RETRYING",
		8: "SHOT_STATUS_FAILED",
		9: "SHOT_STATUS_AWAITING_HUMAN",
	}
	ShotStatus_value = map[string]int32{
		"SHOT_STATUS_UNSPECIFIED":    0,
		"SHOT_STATUS_PENDING":        1,
		"SHOT_STATUS_GENERATING":     2,
		"SHOT_STATUS_RENDERING":      3,
		"SHOT_STATUS_CRITIQUING":     4,
		"SHOT_STATUS_APPROVED":       5,
		"SHOT_STATUS_REJECTED":       6,
		"SHOT_STATUS_RETRYING":       7,
		"SHOT_STATUS_FAILED":         8,
		"SHOT_STATUS_AWAITING_HUMAN": 9,
	}
)

func (x ShotStatus) Enum() *ShotStatus {
	p := new(ShotStatus)
	*p = x
	return p
}

func (x ShotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scidirector_v1_common_proto_enumTypes[2].Descriptor()
}

func (ShotStatus) Type() protoreflect.EnumType {
	return &file_scidirector_v1_common_proto_enumTypes[2]
}

func (x ShotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotStatus.Descriptor instead.
func (ShotStatus) EnumDescriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{2}
}

// 意见来源：VLM 自动审查 or 人类审核员。二者共用同一结构，
// 使 Coder 侧无需区分来源，简化回灌逻辑。
type FeedbackSource int32

const (
	FeedbackSource_FEEDBACK_SOURCE_UNSPECIFIED FeedbackSource = 0
	FeedbackSource_FEEDBACK_SOURCE_VLM         FeedbackSource = 1
	FeedbackSource_FEEDBACK_SOURCE_HUMAN       FeedbackSource = 2
	FeedbackSource_FEEDBACK_SOURCE_SYSTEM      FeedbackSource = 3 // 例如沙盒编译报错，也走同一通道回灌
)

// Enum value maps for FeedbackSource.
var (
	FeedbackSource_name = map[int32]string{
		0: "FEEDBACK_SOURCE_UNSPECIFIED",
		1: "FEEDBACK_SOURCE_VLM",
		2: "FEEDBACK_SOURCE_HUMAN",
		3: "FEEDBACK_SOURCE_SYSTEM",
	}
	FeedbackSource_value = map[string]int32{
		"FEEDBACK_SOURCE_UNSPECIFIED": 0,
		"FEEDBACK_SOURCE_VLM":         1,
		"FEEDBACK_SOURCE_HUMAN":       2,
		"FEEDBACK_SOURCE_SYSTEM":      3,
	}
)

func (x FeedbackSource) Enum() *FeedbackSource {
	p := new(FeedbackSource)
	*p = x
	return p
}

func (x FeedbackSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackSource) Descriptor() protoreflect.EnumDescriptor {
	return file_scidirector_v1_common_proto_enumTypes[3].Descriptor()
}

func (FeedbackSource) Type() protoreflect.EnumType {
	return &file_scidirector_v1_common_proto_enumTypes[3]
}

func (x FeedbackSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackSource.Descriptor instead.
func (FeedbackSource) EnumDescriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{3}
}

// 时间区间，单位为秒。用于镜头时长与字幕轴对齐。
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartSec      float64                `protobuf:"fixed64,1,opt,name=start_sec,json=startSec,proto3" json:"start_sec,omitempty"`
	EndSec        float64                `protobuf:"fixed64,2,opt,name=end_sec,json=endSec,proto3" json:"end_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_scidirector_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStartSec() float64 {
	if x != nil {
		return x.StartSec
	}
	return 0
}

func (x *TimeRange) GetEndSec() float64 {
	if x != nil {
		return x.EndSec
	}
	return 0
}

// 分镜规格：导演智能体的产出，也是全流程的输入。
type ShotSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShotId        string                 `protobuf:"bytes,1,opt,name=shot_id,json=shotId,proto3" json:"shot_id,omitempty"`                                                          // 稳定 ID（由 job_id + index 派生），HITL 重做时按它定位
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                                                                         // 在全片中的序号，从 0 开始
	Narration     string                 `protobuf:"bytes,3,opt,name=narration,proto3" json:"narration,omitempty"`                                                                  // 画外音 / 字幕文本
	VisualBrief   string                 `protobuf:"bytes,4,opt,name=visual_brief,json=visualBrief,proto3" json:"visual_brief,omitempty"`                                           // 视觉意图的自然语言描述（送给 Coder 与 Critic）
	Tag           SceneTag               `protobuf:"varint,5,opt,name=tag,proto3,enum=scidirector.v1.SceneTag" json:"tag,omitempty"`                                                // 场景标签（路由依据）
	Engine        RenderEngine           `protobuf:"varint,6,opt,name=engine,proto3,enum=scidirector.v1.RenderEngine" json:"engine,omitempty"`                                      // 目标渲染引擎
	DurationSec   float64                `protobuf:"fixed64,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`                                         // 目标时长
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`                                                                    // 检索关键词（RAG few-shot / 素材检索）
	Code          string                 `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`                                                                            // 当前版本的渲染源码
	Language      string                 `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`                                                                   // 源码语言：python / html+js
	Meta          map[string]string      `protobuf:"bytes,11,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展位，禁止放二进制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotSpec) Reset() {
	*x = ShotSpec{}
	mi := &file_scidirector_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotSpec) ProtoMessage() {}

func (x *ShotSpec) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotSpec.ProtoReflect.Descriptor instead.
func (*ShotSpec) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ShotSpec) GetShotId() string {
	if x != nil {
		return x.ShotId
	}
	return ""
}

func (x *ShotSpec) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ShotSpec) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *ShotSpec) GetVisualBrief() string {
	if x != nil {
		return x.VisualBrief
	}
	return ""
}

func (x *ShotSpec) GetTag() SceneTag {
	if x != nil {
		return x.Tag
	}
	return SceneTag_SCENE_TAG_UNSPECIFIED
}

func (x *ShotSpec) GetEngine() RenderEngine {
	if x != nil {
		return x.Engine
	}
	return RenderEngine_RENDER_ENGINE_UNSPECIFIED
}

func (x *ShotSpec) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *ShotSpec) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ShotSpec) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShotSpec) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ShotSpec) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 渲染产物：只传「路径与元数据」，视频二进制永远不走 gRPC。
type RenderArtifact struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId       string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ShotId           string                 `protobuf:"bytes,2,opt,name=shot_id,json=shotId,proto3" json:"shot_id,omitempty"`
	VideoPath        string                 `protobuf:"bytes,3,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`          // MP4 片段路径（共享卷或对象存储 key）
	AudioPath        string                 `protobuf:"bytes,4,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`          // TTS 音轨，可空
	SubtitlePath     string                 `protobuf:"bytes,5,opt,name=subtitle_path,json=subtitlePath,proto3" json:"subtitle_path,omitempty"` // 字幕文件，可空
	DurationSec      float64                `protobuf:"fixed64,6,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Width            int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Fps              int32                  `protobuf:"varint,9,opt,name=fps,proto3" json:"fps,omitempty"`
	Attempt          int32                  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`                              // 第几次尝试产出
	Engine           string                 `protobuf:"bytes,11,opt,name=engine,proto3" json:"engine,omitempty"`                                 // 产出引擎名（便于排查是哪个渲染器的问题）
	FrameSamples     []string               `protobuf:"bytes,12,rep,name=frame_samples,json=frameSamples,proto3" json:"frame_samples,omitempty"` // 抽帧 PNG 路径，供 VLM 审查
	RenderedAtUnixMs int64                  `protobuf:"varint,13,opt,name=rendered_at_unix_ms,json=renderedAtUnixMs,proto3" json:"rendered_at_unix_ms,omitempty"`
	RenderCostSec    float64                `protobuf:"fixed64,14,opt,name=render_cost_sec,json=renderCostSec,proto3" json:"render_cost_sec,omitempty"` // 渲染耗时，用于指标
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RenderArtifact) Reset() {
	*x = RenderArtifact{}
	mi := &file_scidirector_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderArtifact) ProtoMessage() {}

func (x *RenderArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderArtifact.ProtoReflect.Descriptor instead.
func (*RenderArtifact) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *RenderArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *RenderArtifact) GetShotId() string {
	if x != nil {
		return x.ShotId
	}
	return ""
}

func (x *RenderArtifact) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

func (x *RenderArtifact) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *RenderArtifact) GetSubtitlePath() string {
	if x != nil {
		return x.SubtitlePath
	}
	return ""
}

func (x *RenderArtifact) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *RenderArtifact) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderArtifact) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderArtifact) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *RenderArtifact) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RenderArtifact) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *RenderArtifact) GetFrameSamples() []string {
	if x != nil {
		return x.FrameSamples
	}
	return nil
}

func (x *RenderArtifact) GetRenderedAtUnixMs() int64 {
	if x != nil {
		return x.RenderedAtUnixMs
	}
	return 0
}

func (x *RenderArtifact) GetRenderCostSec() float64 {
	if x != nil {
		return x.RenderCostSec
	}
	return 0
}

// 审查意见：VLM 与人类共用。
type CriticFeedback struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Passed           bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`                                               // 是否通过
	Score            float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                                                // 0.0 ~ 1.0
	Issues           []string               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`                                                // 发现的问题（可读性、逻辑、节奏…）
	Suggestions      []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`                                      // 【必须可执行】例如「字号 24 -> 48」
	RawResponse      string                 `protobuf:"bytes,5,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`                   // 模型原始输出，用于排查与提示词迭代
	Model            string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`                                                  // 审查所用模型
	Source           FeedbackSource         `protobuf:"varint,7,opt,name=source,proto3,enum=scidirector.v1.FeedbackSource" json:"source,omitempty"`            // 来源
	Attempt          int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`                                             // 这是第几次尝试的审查结果
	LogicScore       float64                `protobuf:"fixed64,9,opt,name=logic_score,json=logicScore,proto3" json:"logic_score,omitempty"`                    // 分维度得分：逻辑一致性
	ReadabilityScore float64                `protobuf:"fixed64,10,opt,name=readability_score,json=readabilityScore,proto3" json:"readability_score,omitempty"` // 分维度得分：文字可读性
	PacingScore      float64                `protobuf:"fixed64,11,opt,name=pacing_score,json=pacingScore,proto3" json:"pacing_score,omitempty"`                // 分维度得分：节奏
	AestheticsScore  float64                `protobuf:"fixed64,12,opt,name=aesthetics_score,json=aestheticsScore,proto3" json:"aesthetics_score,omitempty"`    // 分维度得分：美观度
	CreatedAtUnixMs  int64                  `protobuf:"varint,13,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CriticFeedback) Reset() {
	*x = CriticFeedback{}
	mi := &file_scidirector_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticFeedback) ProtoMessage() {}

func (x *CriticFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticFeedback.ProtoReflect.Descriptor instead.
func (*CriticFeedback) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *CriticFeedback) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CriticFeedback) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CriticFeedback) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *CriticFeedback) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *CriticFeedback) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

func (x *CriticFeedback) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CriticFeedback) GetSource() FeedbackSource {
	if x != nil {
		return x.Source
	}
	return FeedbackSource_FEEDBACK_SOURCE_UNSPECIFIED
}

func (x *CriticFeedback) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *CriticFeedback) GetLogicScore() float64 {
	if x != nil {
		return x.LogicScore
	}
	return 0
}

func (x *CriticFeedback) GetReadabilityScore() float64 {
	if x != nil {
		return x.ReadabilityScore
	}
	return 0
}

func (x *CriticFeedback) GetPacingScore() float64 {
	if x != nil {
		return x.PacingScore
	}
	return 0
}

func (x *CriticFeedback) GetAestheticsScore() float64 {
	if x != nil {
		return x.AestheticsScore
	}
	return 0
}

func (x *CriticFeedback) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

// 流水线事件：Python -> Go 的实时事件，Go 转发给 WebSocket 与 Redis 事件流。
type PipelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ShotId        string                 `protobuf:"bytes,2,opt,name=shot_id,json=shotId,proto3" json:"shot_id,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`                                     // LangGraph 节点名：plan / code / render / critique / revise
	Status        ShotStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=scidirector.v1.ShotStatus" json:"status,omitempty"` // 该 shot 迁移到的状态
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                               // 人类可读的说明，直接展示在 UI 时间线
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ShotIndex     int32                  `protobuf:"varint,7,opt,name=shot_index,json=shotIndex,proto3" json:"shot_index,omitempty"`
	TotalShots    int32                  `protobuf:"varint,8,opt,name=total_shots,json=totalShots,proto3" json:"total_shots,omitempty"`
	Progress      float64                `protobuf:"fixed64,9,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 ~ 1.0 全任务进度
	Artifact      *RenderArtifact        `protobuf:"bytes,10,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Feedback      *CriticFeedback        `protobuf:"bytes,11,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"` // 技术性错误信息（非空时 status 通常为 FAILED）
	TsUnixMs      int64                  `protobuf:"varint,13,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,14,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // 结构化扩展负载（如分镜表快照），保持向后兼容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineEvent) Reset() {
	*x = PipelineEvent{}
	mi := &file_scidirector_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEvent) ProtoMessage() {}

func (x *PipelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEvent.ProtoReflect.Descriptor instead.
func (*PipelineEvent) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PipelineEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PipelineEvent) GetShotId() string {
	if x != nil {
		return x.ShotId
	}
	return ""
}

func (x *PipelineEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PipelineEvent) GetStatus() ShotStatus {
	if x != nil {
		return x.Status
	}
	return ShotStatus_SHOT_STATUS_UNSPECIFIED
}

func (x *PipelineEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PipelineEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *PipelineEvent) GetShotIndex() int32 {
	if x != nil {
		return x.ShotIndex
	}
	return 0
}

func (x *PipelineEvent) GetTotalShots() int32 {
	if x != nil {
		return x.TotalShots
	}
	return 0
}

func (x *PipelineEvent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PipelineEvent) GetArtifact() *RenderArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *PipelineEvent) GetFeedback() *CriticFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *PipelineEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PipelineEvent) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *PipelineEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

// 任务级元信息：用于 REST 查询与前端展示。
type JobProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TotalShots         int32                  `protobuf:"varint,2,opt,name=total_shots,json=totalShots,proto3" json:"total_shots,omitempty"`
	ApprovedShots      int32                  `protobuf:"varint,3,opt,name=approved_shots,json=approvedShots,proto3" json:"approved_shots,omitempty"`
	FailedShots        int32                  `protobuf:"varint,4,opt,name=failed_shots,json=failedShots,proto3" json:"failed_shots,omitempty"`
	AwaitingHumanShots int32                  `protobuf:"varint,5,opt,name=awaiting_human_shots,json=awaitingHumanShots,proto3" json:"awaiting_human_shots,omitempty"`
	Progress           float64                `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	StartedAtUnixMs    int64                  `protobuf:"varint,7,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	UpdatedAtUnixMs    int64                  `protobuf:"varint,8,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_scidirector_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *JobProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgress) GetTotalShots() int32 {
	if x != nil {
		return x.TotalShots
	}
	return 0
}

func (x *JobProgress) GetApprovedShots() int32 {
	if x != nil {
		return x.ApprovedShots
	}
	return 0
}

func (x *JobProgress) GetFailedShots() int32 {
	if x != nil {
		return x.FailedShots
	}
	return 0
}

func (x *JobProgress) GetAwaitingHumanShots() int32 {
	if x != nil {
		return x.AwaitingHumanShots
	}
	return 0
}

func (x *JobProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobProgress) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *JobProgress) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

// 简单健康检查响应，供 Go 侧就绪探针使用。
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_scidirector_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	LlmProvider   string                 `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	VlmModel      string                 `protobuf:"bytes,4,opt,name=vlm_model,json=vlmModel,proto3" json:"vlm_model,omitempty"`
	SandboxReady  bool                   `protobuf:"varint,5,opt,name=sandbox_ready,json=sandboxReady,proto3" json:"sandbox_ready,omitempty"` // Manim/LaTeX 是否可用
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                      // 例如 ["manim", "d3", "vlm"]
	UptimeSec     int64                  `protobuf:"varint,7,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_scidirector_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scidirector_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_scidirector_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *HealthResponse) GetVlmModel() string {
	if x != nil {
		return x.VlmModel
	}
	return ""
}

func (x *HealthResponse) GetSandboxReady() bool {
	if x != nil {
		return x.SandboxReady
	}
	return false
}

func (x *HealthResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HealthResponse) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

var File_scidirector_v1_common_proto protoreflect.FileDescriptor

const file_scidirector_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bscidirector/v1/common.proto\x12\x0escidirector.v1\"A\n" +
	"\tTimeRange\x12\x1b\n" +
	"\tstart_sec\x18\x01 \x01(\x01R\bstartSec\x12\x17\n" +
	"\aend_sec\x18\x02 \x01(\x01R\x06endSec\"\xbc\x03\n" +
	"\bShotSpec\x12\x17\n" +
	"\ashot_id\x18\x01 \x01(\tR\x06shotId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1c\n" +
	"\tnarration\x18\x03 \x01(\tR\tnarration\x12!\n" +
	"\fvisual_brief\x18\x04 \x01(\tR\vvisualBrief\x12*\n" +
	"\x03tag\x18\x05 \x01(\x0e2\x18.scidirector.v1.SceneTagR\x03tag\x124\n" +
	"\x06engine\x18\x06 \x01(\x0e2\x1c.scidirector.v1.RenderEngineR\x06engine\x12!\n" +
	"\fduration_sec\x18\a \x01(\x01R\vdurationSec\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12\x12\n" +
	"\x04code\x18\t \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\n" +
	" \x01(\tR\blanguage\x126\n" +
	"\x04meta\x18\v \x03(\v2\".scidirector.v1.ShotSpec.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x03\n" +
	"\x0eRenderArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x17\n" +
	"\ashot_id\x18\x02 \x01(\tR\x06shotId\x12\x1d\n" +
	"\n" +
	"video_path\x18\x03 \x01(\tR\tvideoPath\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x04 \x01(\tR\taudioPath\x12#\n" +
	"\rsubtitle_path\x18\x05 \x01(\tR\fsubtitlePath\x12!\n" +
	"\fduration_sec\x18\x06 \x01(\x01R\vdurationSec\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\t \x01(\x05R\x03fps\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12\x16\n" +
	"\x06engine\x18\v \x01(\tR\x06engine\x12#\n" +
	"\rframe_samples\x18\f \x03(\tR\fframeSamples\x12-\n" +
	"\x13rendered_at_unix_ms\x18\r \x01(\x03R\x10renderedAtUnixMs\x12&\n" +
	"\x0frender_cost_sec\x18\x0e \x01(\x01R\rrenderCostSec\"\xcc\x03\n" +
	"\x0eCriticFeedback\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06issues\x18\x03 \x03(\tR\x06issues\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12!\n" +
	"\fraw_response\x18\x05 \x01(\tR\vrawResponse\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x126\n" +
	"\x06source\x18\a \x01(\x0e2\x1e.scidirector.v1.FeedbackSourceR\x06source\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x12\x1f\n" +
	"\vlogic_score\x18\t \x01(\x01R\n" +
	"logicScore\x12+\n" +
	"\x11readability_score\x18\n" +
	" \x01(\x01R\x10readabilityScore\x12!\n" +
	"\fpacing_score\x18\v \x01(\x01R\vpacingScore\x12)\n" +
	"\x10aesthetics_score\x18\f \x01(\x01R\x0faestheticsScore\x12+\n" +
	"\x12created_at_unix_ms\x18\r \x01(\x03R\x0fcreatedAtUnixMs\"\xe6\x03\n" +
	"\rPipelineEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\ashot_id\x18\x02 \x01(\tR\x06shotId\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.scidirector.v1.ShotStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"shot_index\x18\a \x01(\x05R\tshotIndex\x12\x1f\n" +
	"\vtotal_shots\x18\b \x01(\x05R\n" +
	"totalShots\x12\x1a\n" +
	"\bprogress\x18\t \x01(\x01R\bprogress\x12:\n" +
	"\bartifact\x18\n" +
	" \x01(\v2\x1e.scidirector.v1.RenderArtifactR\bartifact\x12:\n" +
	"\bfeedback\x18\v \x01(\v2\x1e.scidirector.v1.CriticFeedbackR\bfeedback\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\r \x01(\x03R\btsUnixMs\x12!\n" +
	"\fpayload_json\x18\x0e \x01(\tR\vpayloadJson\"\xb7\x02\n" +
	"\vJobProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vtotal_shots\x18\x02 \x01(\x05R\n" +
	"totalShots\x12%\n" +
	"\x0eapproved_shots\x18\x03 \x01(\x05R\rapprovedShots\x12!\n" +
	"\ffailed_shots\x18\x04 \x01(\x05R\vfailedShots\x120\n" +
	"\x14awaiting_human_shots\x18\x05 \x01(\x05R\x12awaitingHumanShots\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12+\n" +
	"\x12started_at_unix_ms\x18\a \x01(\x03R\x0fstartedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\b \x01(\x03R\x0fupdatedAtUnixMs\"\x0f\n" +
	"\rHealthRequest\"\xec\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12\x1b\n" +
	"\tvlm_model\x18\x04 \x01(\tR\bvlmModel\x12#\n" +
	"\rsandbox_ready\x18\x05 \x01(\bR\fsandboxReady\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\a \x01(\x03R\tuptimeSec*y\n" +
	"\bSceneTag\x12\x19\n" +
	"\x15SCENE_TAG_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSCENE_TAG_MATH\x10\x01\x12\x12\n" +
	"\x0eSCENE_TAG_DATA\x10\x02\x12\x12\n" +
	"\x0eSCENE_TAG_CODE\x10\x03\x12\x16\n" +
	"\x12SCENE_TAG_AMBIENCE\x10\x04*\xad\x01\n" +
	"\fRenderEngine\x12\x1d\n" +
	"\x19RENDER_ENGINE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RENDER_ENGINE_MANIM\x10\x01\x12\x14\n" +
	"\x10RENDER_ENGINE_D3\x10\x02\x12\x19\n" +
	"\x15RENDER_ENGINE_ECHARTS\x10\x03\x12\x1b\n" +
	"\x17RENDER_ENGINE_CODE_ANIM\x10\x04\x12\x17\n" +
	"\x13RENDER_ENGINE_STOCK\x10\x05*\x9b\x02\n" +
	"\n" +
	"ShotStatus\x12\x1b\n" +
	"\x17SHOT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SHOT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16SHOT_STATUS_GENERATING\x10\x02\x12\x19\n" +
	"\x15SHOT_STATUS_RENDERING\x10\x03\x12\x1a\n" +
	"\x16SHOT_STATUS_CRITIQUING\x10\x04\x12\x18\n" +
	"\x14SHOT_STATUS_APPROVED\x10\x05\x12\x18\n" +
	"\x14SHOT_STATUS_REJECTED\x10\x06\x12\x18\n" +
	"\x14SHOT_STATUS_RETRYING\x10\a\x12\x16\n" +
	"\x12SHOT_STATUS_FAILED\x10\b\x12\x1e\n" +
	"\x1aSHOT_STATUS_AWAITING_HUMAN\x10\t*\x81\x01\n" +
	"\x0eFeedbackSource\x12\x1f\n" +
	"\x1bFEEDBACK_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FEEDBACK_SOURCE_VLM\x10\x01\x12\x19\n" +
	"\x15FEEDBACK_SOURCE_HUMAN\x10\x02\x12\x1a\n" +
	"\x16FEEDBACK_SOURCE_SYSTEM\x10\x03BQZOgithub.com/itJinYu/SciDirector/backend/internal/pb/scidirector/v1;scidirectorv1b\x06proto3"

var (
	file_scidirector_v1_common_proto_rawDescOnce sync.Once
	file_scidirector_v1_common_proto_rawDescData []byte
)

func file_scidirector_v1_common_proto_rawDescGZIP() []byte {
	file_scidirector_v1_common_proto_rawDescOnce.Do(func() {
		file_scidirector_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scidirector_v1_common_proto_rawDesc), len(file_scidirector_v1_common_proto_rawDesc)))
	})
	return file_scidirector_v1_common_proto_rawDescData
}

var file_scidirector_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_scidirector_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scidirector_v1_common_proto_goTypes = []any{
	(SceneTag)(0),          // 0: scidirector.v1.SceneTag
	(RenderEngine)(0),      // 1: scidirector.v1.RenderEngine
	(ShotStatus)(0),        // 2: scidirector.v1.ShotStatus
	(FeedbackSource)(0),    // 3: scidirector.v1.FeedbackSource
	(*TimeRange)(nil),      // 4: scidirector.v1.TimeRange
	(*ShotSpec)(nil),       // 5: scidirector.v1.ShotSpec
	(*RenderArtifact)(nil), // 6: scidirector.v1.RenderArtifact
	(*CriticFeedback)(nil), // 7: scidirector.v1.CriticFeedback
	(*PipelineEvent)(nil),  // 8: scidirector.v1.PipelineEvent
	(*JobProgress)(nil),    // 9: scidirector.v1.JobProgress
	(*HealthRequest)(nil),  // 10: scidirector.v1.HealthRequest
	(*HealthResponse)(nil), // 11: scidirector.v1.HealthResponse
	nil,                    // 12: scidirector.v1.ShotSpec.MetaEntry
}
var file_scidirector_v1_common_proto_depIdxs = []int32{
	0,  // 0: scidirector.v1.ShotSpec.tag:type_name -> scidirector.v1.SceneTag
	1,  // 1: scidirector.v1.ShotSpec.engine:type_name -> scidirector.v1.RenderEngine
	12, // 2: scidirector.v1.ShotSpec.meta:type_name -> scidirector.v1.ShotSpec.MetaEntry
	3,  // 3: scidirector.v1.CriticFeedback.source:type_name -> scidirector.v1.FeedbackSource
	2,  // 4: scidirector.v1.PipelineEvent.status:type_name -> scidirector.v1.ShotStatus
	6,  // 5: scidirector.v1.PipelineEvent.artifact:type_name -> scidirector.v1.RenderArtifact
	7,  // 6: scidirector.v1.PipelineEvent.feedback:type_name -> scidirector.v1.CriticFeedback
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_scidirector_v1_common_proto_init() }
func file_scidirector_v1_common_proto_init() {
	if File_scidirector_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scidirector_v1_common_proto_rawDesc), len(file_scidirector_v1_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scidirector_v1_common_proto_goTypes,
		DependencyIndexes: file_scidirector_v1_common_proto_depIdxs,
		EnumInfos:         file_scidirector_v1_common_proto_enumTypes,
		MessageInfos:      file_scidirector_v1_common_proto_msgTypes,
	}.Build()
	File_scidirector_v1_common_proto = out.File
	file_scidirector_v1_common_proto_goTypes = nil
	file_scidirector_v1_common_proto_depIdxs = nil
}
